version: "3.9"
services:
  mhbabu-web-service:
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
    image: ${CONTAINER_NAME}:latest
    restart: always
    volumes:
      - ../../:/app
      - /app/node_modules
    env_file:
      - ../../.env
    ports:
      - ${EXTERNAL_PORT}:${PORT}
    networks:
      mhbabu-web-service-network:

networks:
  mhbabu-web-service-network:
